### ISSUE TITLE
Provide better support for building

### ISSUE THREAD

**Issue by deem0n** [transceptor-technology/siridb-server#52]
Hello, trying to build on Mac OS X.

Is it possible to regenerate *.mk files with custom gcc options ? Or may be you can update all *.mk files in your repo to include standard env vars CFLAGS and  LDFLAGS ?

For example to build on mac os x I need to edit Build/src/test/subdir.mk like this:

```
# Each subdirectory must supply rules for building sources it contributes
src/test/%.o: ../src/test/%.c
        @echo 'Building file: $<'
        @echo 'Invoking: GCC C Compiler'
        gcc -I../include $(CFLAGS) -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
        @echo 'Finished building: $<'
        @echo ' '
```
Before `make` I just set CFLAGS like this:
`export CFLAGS="-I/usr/local/include -I/usr/local/Cellar/pcre/8.39/include"`

Thanks

**Comment by joente** [comment]
CFLAGS and LDFLAGS environment vars are now included in all mk files.

**Comment by deem0n** [comment]
Thanks!

Actually there is no problems to compile, apart from crypt_r. I will try to make a pull request with my macosx specific changes 

```
DmitrijeevsMBP3:Release deem0n$ ./siridb-server
[I 2017-02-22 13:02:07] Starting SiriDB Server (version: 2.0.13)
[C 2017-02-22 13:02:07] Could not read '/etc/siridb/siridb.conf': error: cannot open file for reading

DmitrijeevsMBP3:Release deem0n$ uname -a
Darwin Dmitrij-Dorofeevs-MacBook-Pro-3.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

**Comment by joente** [comment]
Thanks, your help is very much appreciated. I look forward to your pull request!

**Comment by joente** [comment]
Created issue #54 for removing crypt dependency on mac osx.

**Comment by joente** [comment]
@deem0n, building SiriDB should now completely work on osx. One thing you probably need to change is the `max_open_files` value in `siridb.conf`. This is set by default to a relative high value. On Linux we change the soft limit if needed but on osx a value this high cannot be set. SiriDB runs fine with any value, for example 512 is probably good enough.
