### ISSUE TITLE
cleri fails to parse queries on 32bit armhf (rpi) - debian jessie

### ISSUE THREAD

**Issue by AlmiS** [transceptor-technology/siridb-server#53]
After compiling the Debug version of the server on a raspberry pi with 32bit raspbian jessie, the cleri test fails in the very first assertion. While data can be inserted to the db, any query to the server results in the following error: 

_`(CPROTO_ERR_QUERY) Query error at position 0. Expecting timeit or end_of_statement`_

Is this an issue with the 32bit OS? I suspect the grammar is not compiled correctly with libpcre3-dev on a 32bit CPU / OS.

**Comment by joente** [comment]
I found one mistake in `choice.c` where I was pointing to a sequence list. The memory positions for a choice and sequence is the same on 64bit but they are different on 32bit. 

@AlmiS, could you try to pull and build again?

**Comment by joente** [comment]
Issue is fixed. Compiling on 32bit systems should work now.

**Comment by AlmiS** [comment]
You are a genius @joente. 
I just tested on the rpi and it works. Thank you for responding so fast, and thank you for open sourcing this great software!
