### ISSUE TITLE
Remove crypt dependency for building on Mac (osx)

### ISSUE THREAD

**Issue by joente** [transceptor-technology/siridb-server#54]
For storing user passwords the crypt lib is used. When building on osx the crypt lib is not available and therefore the build fails.

**Comment by joente** [comment]
Created a custom one-way encryption function for storing passwords. For backwards compatibility, building on linux still requires the crypt lib. New passwords are always stored using the custom algorithm but validating password on linux is first done using the new function and has a fallback with the old crypt function.

**Comment by oleid** [comment]
You should never ever use non cryptographic RNGs when doing crypto stuff. First rule of cryptgraphy: never create your own ;)

How about using e.g. libsodium? It it's proven and has a nice C API.
