### ISSUE TITLE
Request timed out (CPROTO_REQ_QUERY)

### ISSUE THREAD

**Issue by FilipJanitor** [transceptor-technology/siridb-server#65]
Hello, as I mentioned in #64 I am using your database to work with some queries, that reach ~180 000 000 points. After installing latest release, and changing the limit of selected points, many partial queries run flawlessly. However,  after executing queries, that reach around ~20 000 000 points, I started getting  these errors in prompt:

`Request timed out on PID 23 (CPROTO_REQ_QUERY) (You might receive another error 'Package ID not found' if the result arrives)`

 After throwing this error, the server is responsive and is able to execute other queries, but the HW doesn't seem to be under much load (I would expect it to be under load when executing the query but this is subjective observation). After couple of minutes, the expected error comes, but apart from that, no result is displayed:

`Package ID not found: 11 (CPROTO_RES_QUERY)`

What does that mean and what can I do about it please ?
Thanks a lot for help.

**Comment by joente** [comment]
This is because the client has a timeout and has cancelled the query. The server did perform the query but not within the maximum allowed time. Timeouts are set to a relative short time by default but this was done with the 1 million limit in mind. Did this timeout occur in `siridb-prompt`?

**Comment by FilipJanitor** [comment]
Yes, was working with siridb-prompt when those errors occured.

**Comment by joente** [comment]
Timeout for the client is configurable and the timeout of siridb-prompt is set to 10 minutes which should be sufficient, even for large queries.
