### ISSUE TITLE
Native Client for NodeJS

### ISSUE THREAD

**Issue by beegmon** [transceptor-technology/siridb-server#80]
Is there planned support for a native nodejs client utilizing libsiridb as a C addon?

I can make due with the HTTP interface for now, but you would love to have a native nodejs client to reduce the HTTP overhead.

**Comment by joente** [comment]
I like the idea for creating a nodejs addon. Since nodejs is running on libuv it will probably not be very hard to write the addon. I will take a look at this soon.

**Comment by joente** [comment]
Added the following repo: https://github.com/transceptor-technology/siridb-nodejs-addon

The concept already works but I still need to make the `insert` handler. In this concept the `query` data is returned as a json string which is a little inefficient since we could just as well return a JavaScript Object immediately. To Be Continued...

**Comment by joente** [comment]
query handler now returns a Javascript Object. For example:
```javascript
siridb.query("select * from 'aggr'", (resp, status) => {
    console.log(status);  /* 0 when successful, or a negative value 
                             in case of an error */
    console.log(resp);  /* response data or in case of an error 
                           resp.err_msg contains a description */
    
    /*
    Example response:

    { aggr: 
       [ [ 1447249033, 531 ],
         [ 1447249337, 534 ],
         [ 1447249633, 535 ],
         [ 1447249937, 531 ],
         [ 1447250249, 532 ],
         [ 1447250549, 537 ],
         [ 1447250868, 530 ],
         [ 1447251168, 520 ],
         [ 1447251449, 54 ],
         [ 1447251749, 54 ],
         [ 1447252049, 513 ],
         [ 1447252349, 537 ],
         [ 1447252649, 528 ],
         [ 1447252968, 531 ],
         [ 1447253244, 533 ],
         [ 1447253549, 538 ],
         [ 1447253849, 534 ],
         [ 1447254149, 532 ],
         [ 1447254449, 533 ],
         [ 1447254748, 537 ] ] }

    Another example response (error):

    { error_msg: 
        'Query error at position 9. Expecting =>, prefix, suffix, , or from' }
    
    */
}); 
```

**Comment by joente** [comment]
Insert handler is created, for example:
```javascript
siridb.insert([{
    type: 'float',
    name: 'some float series',
    points: [
        [1505118253, 5.4],
        [1505118307, 7.1]
    ]
}, {
    type: 'integer',
    name: 'some integer series',
    points: [
        [1505118253, 5],
        [1505118307, 7]
    ]
}], (resp, status) => {
    // status == 0 when successful
    // resp.success_msg contains a success message and in case of an
    // error resp.error_msg contains details about the error.
}); 
```

**Comment by joente** [comment]
Hostname resolving is implemented. The address can now be an IPv4, IPv6 or a DNS name.

Release an initial version: https://github.com/transceptor-technology/siridb-nodejs-addon/tree/0.0.1

**Comment by beegmon** [comment]
This is awesome thank you! 

I will have some time in the next couple of week to give this a shot, but thank you so much for implementing this!

**Comment by joente** [comment]
You're welcome!
