### ISSUE TITLE
can't building

### ISSUE THREAD

**Issue by hackersean** [transceptor-technology/siridb-server#81]
for (int i = 0; i < ACCESS_SIZE; i++) 
it is not standard of c
why not use c++

**Comment by joente** [comment]
I guess you talk about the initialization of `i` inside the `for` loop? This is introduced in C99... The project is written in C, not C++.

To solve your issue, try to set the following CFLAGS: 
`export CFLAGS="-std=c99 -D_GNU_SOURCE"`
