### ISSUE TITLE
Size of Int

### ISSUE THREAD

**Issue by beegmon** [transceptor-technology/siridb-server#83]
Is it safe to assume that siridb, when running on 64bit platform, uses a 64bit int when feeding it integer point values?

Also, is that int signed or unsigned?

Thanks!

**Comment by joente** [comment]
SiriDB is using 64 bit signed integers for integer values. Note that timestamps are stored with 32bit unsigned integers when using a second time precision and with millisecond precision or greater they are stored as 64bit unsigned integers. (You can save some disk space by creating a database with second precision)

Cheers!
