### ISSUE TITLE
logical errors/type mismatch in sirinet_socket_on_data()

### ISSUE THREAD

**Issue by edwin-oetelaar** [transceptor-technology/siridb-server#85]
https://github.com/transceptor-technology/siridb-server/blob/8fbf19982ae9eb4cb444134ea728a3069efafe3f/src/siri/net/socket.c#L166

I found 2 errors here

if (nread < 0) // check if less than 0
    {
        if (nread != UV_EOF) // check if not UV_EOF (will always be true, UV_EOF == 1)
        {
            log_error("Read error: %s", uv_err_name(nread)); // type mismatch, uv_err_name() does not take a ssize_t as an argument, it needs uv_err_t
        }
        QUIT_SOCKET
    }

**Comment by edwin-oetelaar** [comment]
Update, I have been using libuv version 0.10 instead of 1.x
- this still does not make the code OK, the signature is : `const char* uv_err_name(int err)`
this means the `err` should be a valid error code not a negative number

**Comment by edwin-oetelaar** [comment]
It appears that I have a configuration problem, the code looks like the canonical example from the libuv documenation, sorry about the noise.

Ik a eerst al mijn libraries maar eens bijwerken alvorens ik weer wat ga zeggen hier, succes heren.

**Comment by joente** [comment]
No problem, thanks for looking into the source code so quickly!
