### ISSUE TITLE
building fails due to missing libcleri header files (please update documentation)

### ISSUE THREAD

**Issue by paulgevers** [transceptor-technology/siridb-server#88]
While trying to build siridb-server, my build fails due to missing libcleri header files:
```
/usr/bin/make --directory=Release
make[2]: Entering directory '/<<PKGBUILDDIR>>/Release'

<cut unrelevant part>

Building file: ../src/test/test.c
Invoking: GCC C Compiler
gcc -I../include -O3 -Wall -Wextra -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -c -fmessage-length=0 -MMD -MP -MF"src/test/test.d" -MT"src/test/test.o" -o "src/test/test.o" "../src/test/test.c"
../src/test/test.c:21:10: fatal error: cleri/cleri.h: No such file or directory
 #include <cleri/cleri.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/test/subdir.mk:18: recipe for target 'src/test/test.o' failed
```
I guess that since the split of libcleri, the build now also depends on "libcleri-dev". This should be documented in the README.md file.

**Comment by joente** [comment]
In the current README.md we have a section 'Compile from source' where we note the requirement for libcleri. 

>From version 2.0.19 libcleri is not included as part of this source anymore and needs to be installed separately. libcleri can be found here: https://github.com/transceptor-technology/libcleri

Maybe we should instead include the installation steps for libcleri inside the README.md?

**Comment by paulgevers** [comment]
No, I just think you should remove the quotes, i.e. make the letters black. The gray letters fooled me. Also, I jumped straight at "Linux", but that may be me.

**Comment by paulgevers** [comment]
Ehm, yes, maybe some installation steps.
