### ISSUE TITLE
What distributed algorithm use ?

### ISSUE THREAD

**Issue by hawrre** [transceptor-technology/siridb-server#92]
Hi, 
congrats on new project,
I have look over some you're source code but I can't find out  which distributed algorithm or way do you use for SiriDB ? consistent hashing ? raft or ...

**Comment by joente** [comment]
Thanks, Time Series in SiriDB are distributed across pools using something quite similar to consistent hashing. A hash table is pre-computed available on each node in a cluster so a quick lookup can be done to determine in which pool time-series should 'live'.
