### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ieipi** [transceptor-technology/siridb-server#95]
when follow the build process in the wiki site, it failed with following error message:

../include/siri/grammar/grammar.h:13:10: fatal error: 'cleri/cleri.h' file not found

**Comment by joente** [comment]
From version 2.0.19 libcleri is not included as part of this source anymore and needs to be installed separately. libcleri can be found here: https://github.com/transceptor-technology/libcleri

**Comment by tamoyal** [comment]
@joente worth adding to the README

**Comment by riklempens** [comment]
@tamoyal it is mentioned in the README in the compile from source section.

**Comment by tamoyal** [comment]
@riklempens True. Under the Ubuntu section which i skipped since I installed on OS X
